# Generated by Django 2.2.3 on 2019-07-23 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime(2019, 7, 23, 10, 10, 43, 643247, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2019, 7, 23, 10, 10, 43, 643247, tzinfo=utc))),
                ('rent_type', models.IntegerField(default=-1)),
                ('roomate_num', models.IntegerField(default=-1)),
                ('building_type', models.IntegerField(default=-1)),
                ('period', models.IntegerField(default=-1)),
                ('cost', models.IntegerField(default=-1)),
                ('university', models.IntegerField(default=-1)),
                ('gender', models.IntegerField(default=-1)),
                ('addr_gu', models.CharField(max_length=5)),
                ('addr_dong', models.CharField(max_length=5)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('detail', models.TextField(default='')),
                ('deposit', models.IntegerField(default=-1)),
                ('rooms', models.IntegerField(default=-1)),
            ],
        ),
    ]
