# Generated by Django 2.2.3 on 2019-07-23 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_auto_20190723_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 10, 32, 33, 584102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 10, 32, 33, 584102, tzinfo=utc)),
        ),
    ]
